//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XtremePharmacyManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the server to update your user account.
        ///Please check your application settings to ensure you have a proper connection to the database or contact a system administrator. .
        /// </summary>
        internal static string AccountSettingsErrorMessage {
            get {
                return ResourceManager.GetString("AccountSettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have empty username or password.
        ///If you still can&apos;t update your account ask the administrator for a solution to the problem..
        /// </summary>
        internal static string AccountSettingsInvalidCredentialsErrorMessage {
            get {
                return ResourceManager.GetString("AccountSettingsInvalidCredentialsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile picture for your account.
        /// </summary>
        internal static string AccountSettingsProfilePicSelectTitle {
            get {
                return ResourceManager.GetString("AccountSettingsProfilePicSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string AccountSettingsTitle {
            get {
                return ResourceManager.GetString("AccountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of this application can be run at a time!.
        /// </summary>
        internal static string ApplicationInstanceErrorMessage {
            get {
                return ResourceManager.GetString("ApplicationInstanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the application settings will take effect after restarting the application..
        /// </summary>
        internal static string ApplicationSettingsChangeNotice {
            get {
                return ResourceManager.GetString("ApplicationSettingsChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save your logins into and load them from.....
        /// </summary>
        internal static string ApplicationSettingsLoginsFolderSelectTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsLoginsFolderSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to get the report files from....
        /// </summary>
        internal static string ApplicationSettingsReportsFolderSelectTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsReportsFolderSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string ApplicationSettingsTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XtremePharmacyManager.
        /// </summary>
        internal static string AssemblyProductName {
            get {
                return ResourceManager.GetString("AssemblyProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XtremePharmacyManager.
        /// </summary>
        internal static string AssemblyTitle {
            get {
                return ResourceManager.GetString("AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple login results gotten or none at all.
        ///Please check the credentials and try again..
        /// </summary>
        internal static string AuthorisationAddLoginInvalidResultsMessage {
            get {
                return ResourceManager.GetString("AuthorisationAddLoginInvalidResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully found your credentials by the configuration settings of your application.
        ///On your confirmation by logging in this will be the user you will work with.
        ///If you want another user select from the logins list.
        ///Every login is saved into the filesystem in a binary format read only this program..
        /// </summary>
        internal static string AuthorisationAppConfLoginFoundMessage {
            get {
                return ResourceManager.GetString("AuthorisationAppConfLoginFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with the specified credentials by your application configuration.
        ///Please configure the application with database credentials provided by your system administrator or create an user with the stored procedures and set it as a sysadmin if you are a system administrator and try again.
        ///The admin role for the database is different from the sysadmin role and this is for security reasons..
        /// </summary>
        internal static string AuthorisationAppConfLoginNotFoundMessage {
            get {
                return ResourceManager.GetString("AuthorisationAppConfLoginNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use this application without a proper authorization in the database and closing the login without even confirming or cancelling it will not help you. Application will exit!.
        /// </summary>
        internal static string AuthorisationErrorCancelledLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorCancelledLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is only for administrators and employees! 
        ///Client use of it is unauthorized and the application will exit!.
        /// </summary>
        internal static string AuthorisationErrorClientLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorClientLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user currently logged in. Application will exit!.
        /// </summary>
        internal static string AuthorisationErrorNoLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorNoLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you are the system administrator for the database and you have either disabled or bypassed the logon trigger and that&apos;s why you were probably connected even if you didn&apos;t have credentials to connect to the database.
        ///This might damage the system and enabling the trigger is critical.
        ///This is an important warning because the system is at risk of data breach in multiple ways..
        /// </summary>
        internal static string AuthorisationErrorSysAdminBreachMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorSysAdminBreachMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an administrator.
        ///You have access to everything in the database.
        ///Everything is created, altered and deleted using stored procedures so the database will calculate some of the things for you..
        /// </summary>
        internal static string AuthorisationLoginAdminNotice {
            get {
                return ResourceManager.GetString("AuthorisationLoginAdminNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an employee, you have limited access to the features of this application.
        ///Your permissions:
        ///1.Add, edit, delete product images
        ///2.Generate product reports
        ///3.Add, edit, delete and/or generate reports for product orders
        ///4.Add, edit, delete and/or generate reports for order deliveries
        ///5.View logs
        ///6.View the rest of the tables with read-only permissions.
        ///The bulk operations enabled for you are for product images, product orders and order deliveries.
        ///Everything is created, altered and deleted usi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthorisationLoginEmployeeNotice {
            get {
                return ResourceManager.GetString("AuthorisationLoginEmployeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you didn&apos;t provide any login information at all.
        ///Please try again..
        /// </summary>
        internal static string AuthorisationLoginEmptyInputMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginEmptyInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Logins list hasn&apos;t been retrieved properly.
        ///Please restart the application..
        /// </summary>
        internal static string AuthorisationLoginFilesystemLoadErrorMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginFilesystemLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with the specified credentials by your input.
        ///Please input the credentials you registered with or provided by your system administrator..
        /// </summary>
        internal static string AuthorisationLoginInvalidInputMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginInvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is not connected to the database and login information cannot be retrieved.
        ///Please retry..
        /// </summary>
        internal static string AuthorisationLoginNoConnectionMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginNoConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product brands..
        /// </summary>
        internal static string BrandDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("BrandDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product brands..
        /// </summary>
        internal static string BrandEditOperationPermissionError {
            get {
                return ResourceManager.GetString("BrandEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string BrandMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BrandMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Brand Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkBrandMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkBrandMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been added..
        /// </summary>
        internal static string BulkBrandOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been deleted..
        /// </summary>
        internal static string BulkBrandOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product brands..
        /// </summary>
        internal static string BulkBrandOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product brands is done only by the administrators of this system...
        /// </summary>
        internal static string BulkBrandOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been updated..
        /// </summary>
        internal static string BulkBrandOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Delivery Service Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkDeliveryServiceMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been added..
        /// </summary>
        internal static string BulkDeliveryServiceOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been deleted..
        /// </summary>
        internal static string BulkDeliveryServiceOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for delivery services..
        /// </summary>
        internal static string BulkDeliveryServiceOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for delivery services is done only by the administrators of this system...
        /// </summary>
        internal static string BulkDeliveryServiceOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been updated..
        /// </summary>
        internal static string BulkDeliveryServiceOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operations:.
        /// </summary>
        internal static string BulkOperationCompletedCountMessage {
            get {
                return ResourceManager.GetString("BulkOperationCompletedCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations finished. Time finished:.
        /// </summary>
        internal static string BulkOperationEndTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationEndTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code:.
        /// </summary>
        internal static string BulkOperationErrorCodeMessage {
            get {
                return ResourceManager.GetString("BulkOperationErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        internal static string BulkOperationErrorMessage {
            get {
                return ResourceManager.GetString("BulkOperationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing operation:.
        /// </summary>
        internal static string BulkOperationExecutingMessage {
            get {
                return ResourceManager.GetString("BulkOperationExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Time:.
        /// </summary>
        internal static string BulkOperationExecutionTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationExecutionTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Operations:.
        /// </summary>
        internal static string BulkOperationFailedCountMessage {
            get {
                return ResourceManager.GetString("BulkOperationFailedCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. Here are details:.
        /// </summary>
        internal static string BulkOperationFailedMessage {
            get {
                return ResourceManager.GetString("BulkOperationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation on.
        /// </summary>
        internal static string BulkOperationOperationOnName {
            get {
                return ResourceManager.GetString("BulkOperationOperationOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ID:.
        /// </summary>
        internal static string BulkOperationOperatonOnTargetIDName {
            get {
                return ResourceManager.GetString("BulkOperationOperatonOnTargetIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this as a bulk operation?.
        /// </summary>
        internal static string BulkOperationQuestion {
            get {
                return ResourceManager.GetString("BulkOperationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Results:.
        /// </summary>
        internal static string BulkOperationResultsMessage {
            get {
                return ResourceManager.GetString("BulkOperationResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations started executing at:.
        /// </summary>
        internal static string BulkOperationStartTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationStartTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Operations.
        /// </summary>
        internal static string BulkOperationsTitle {
            get {
                return ResourceManager.GetString("BulkOperationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful.Output:.
        /// </summary>
        internal static string BulkOperationSuccessfulMessage {
            get {
                return ResourceManager.GetString("BulkOperationSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An access exception occured and this operation cannot be executed..
        /// </summary>
        internal static string BulkOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Order Delivery Operation access is given only to administrators and employees of this system..
        /// </summary>
        internal static string BulkOrderDeliveryMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been added..
        /// </summary>
        internal static string BulkOrderDeliveryOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been deleted..
        /// </summary>
        internal static string BulkOrderDeliveryOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for order deliveries..
        /// </summary>
        internal static string BulkOrderDeliveryOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for order deliveries is done only by the administrators and employees of this system...
        /// </summary>
        internal static string BulkOrderDeliveryOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been updated..
        /// </summary>
        internal static string BulkOrderDeliveryOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Payment Method Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkPaymentMethodMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been added..
        /// </summary>
        internal static string BulkPaymentMethodOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been deleted..
        /// </summary>
        internal static string BulkPaymentMethodOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for payment methods..
        /// </summary>
        internal static string BulkPaymentMethodOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for payment methods is done only by the administrators of this system...
        /// </summary>
        internal static string BulkPaymentMethodOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been updated..
        /// </summary>
        internal static string BulkPaymentMethodOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Image Operation access is given only to administrators and employees of this system..
        /// </summary>
        internal static string BulkProductImageMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductImageMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been added..
        /// </summary>
        internal static string BulkProductImageOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been deleted..
        /// </summary>
        internal static string BulkProductImageOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product images..
        /// </summary>
        internal static string BulkProductImageOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product images is done only by the administrators and employees of this system...
        /// </summary>
        internal static string BulkProductImageOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been updated..
        /// </summary>
        internal static string BulkProductImageOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkProductMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been added..
        /// </summary>
        internal static string BulkProductOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been deleted..
        /// </summary>
        internal static string BulkProductOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for products..
        /// </summary>
        internal static string BulkProductOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for products is done only by the administrators of this system...
        /// </summary>
        internal static string BulkProductOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been updated..
        /// </summary>
        internal static string BulkProductOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Order Operation access is given only to administrators and employees of this system..
        /// </summary>
        internal static string BulkProductOrderMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been added..
        /// </summary>
        internal static string BulkProductOrderOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been deleted..
        /// </summary>
        internal static string BulkProductOrderOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product orders..
        /// </summary>
        internal static string BulkProductOrderOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product orders is done only by the administrators and employees of this system...
        /// </summary>
        internal static string BulkProductOrderOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been updated..
        /// </summary>
        internal static string BulkProductOrderOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want the bulk order operation to add order with total price override on create?.
        /// </summary>
        internal static string BulkProductOrderTotalPriceOverrideQuestion {
            get {
                return ResourceManager.GetString("BulkProductOrderTotalPriceOverrideQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk User Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkUserMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkUserMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added..
        /// </summary>
        internal static string BulkUserOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted..
        /// </summary>
        internal static string BulkUserOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for users..
        /// </summary>
        internal static string BulkUserOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for users is done only by the administrators of this system...
        /// </summary>
        internal static string BulkUserOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated..
        /// </summary>
        internal static string BulkUserOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Vendor Operation access is given only to administrators of this system..
        /// </summary>
        internal static string BulkVendorMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkVendorMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been added..
        /// </summary>
        internal static string BulkVendorOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been deleted..
        /// </summary>
        internal static string BulkVendorOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product vendors..
        /// </summary>
        internal static string BulkVendorOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product vendors is done only by the administrators of this system...
        /// </summary>
        internal static string BulkVendorOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been updated..
        /// </summary>
        internal static string BulkVendorOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close? All unsaved changes incl. bulk operations will be lost.
        /// </summary>
        internal static string ClosePrompt {
            get {
                return ResourceManager.GetString("ClosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ClosePromptTitle {
            get {
                return ResourceManager.GetString("ClosePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect even after a retry. Application will exit....
        /// </summary>
        internal static string ConnectionFailedAfterRetryMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedAfterRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect and login to the database. 
        ///This was not supposed to happen so contact the system administrator and/or check the application configuration....
        /// </summary>
        internal static string ConnectionFailedLoginMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error. 
        ///Please check the application configuration and/or contact your system administrator.
        /// </summary>
        internal static string ConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connection and login to the database. Now you are ready to go..
        /// </summary>
        internal static string ConnectionSuccessfulLoginMessage {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successfuly open..
        /// </summary>
        internal static string ConnectionSuccessfulMessage {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception details:
        ///.
        /// </summary>
        internal static string CriticalErrorInnerExceptionDetails {
            get {
                return ResourceManager.GetString("CriticalErrorInnerExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critcal Error: An exception occured.
        /// </summary>
        internal static string CriticalErrorMessage {
            get {
                return ResourceManager.GetString("CriticalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        internal static string CriticalErrorTitle {
            get {
                return ResourceManager.GetString("CriticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Host.
        /// </summary>
        internal static string CurrentHostTitle {
            get {
                return ResourceManager.GetString("CurrentHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Operator.
        /// </summary>
        internal static string CurrentOperatorTitle {
            get {
                return ResourceManager.GetString("CurrentOperatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete delivery services..
        /// </summary>
        internal static string DeliveryServiceDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("DeliveryServiceDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit delivery services..
        /// </summary>
        internal static string DeliveryServiceEditOperationPermissionError {
            get {
                return ResourceManager.GetString("DeliveryServiceEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string DeliveryServiceMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("DeliveryServiceMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image to test the conversion capabilities...
        /// </summary>
        internal static string ImageBinConverterConvertImageTitle {
            get {
                return ResourceManager.GetString("ImageBinConverterConvertImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image to upload or for add/update operation....
        /// </summary>
        internal static string ImageUploadForOperationTitle {
            get {
                return ResourceManager.GetString("ImageUploadForOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language already exists!.
        /// </summary>
        internal static string LanguageManagerLanguageExistErrorMessage {
            get {
                return ResourceManager.GetString("LanguageManagerLanguageExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language wasn&apos;t added in the first place or was removed.
        /// </summary>
        internal static string LanguageManagerLanguageNonexistentErrorMessage {
            get {
                return ResourceManager.GetString("LanguageManagerLanguageNonexistentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Results:.
        /// </summary>
        internal static string lblBulkOperationResultsText {
            get {
                return ResourceManager.GetString("lblBulkOperationResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Logs access is given only to administrators and employees of this system..
        /// </summary>
        internal static string LogsMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("LogsMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        internal static string NewOrderTitle {
            get {
                return ResourceManager.GetString("NewOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete order deliveries..
        /// </summary>
        internal static string OrderDeliveryDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("OrderDeliveryDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit order deliveries..
        /// </summary>
        internal static string OrderDeliveryEditOperationPermissionError {
            get {
                return ResourceManager.GetString("OrderDeliveryEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate invoice for this order delivery?.
        /// </summary>
        internal static string OrderDeliveryInvoiceGenerationQuestion {
            get {
                return ResourceManager.GetString("OrderDeliveryInvoiceGenerationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Deliveries list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string OrderDeliveryMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("OrderDeliveryMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete payment methods..
        /// </summary>
        internal static string PaymentMethodDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("PaymentMethodDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit payment methods..
        /// </summary>
        internal static string PaymentMethodEditOperationPermissionError {
            get {
                return ResourceManager.GetString("PaymentMethodEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string PaymentMethodMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("PaymentMethodMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete products..
        /// </summary>
        internal static string ProductDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit products..
        /// </summary>
        internal static string ProductEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product images..
        /// </summary>
        internal static string ProductImageDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductImageDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product images..
        /// </summary>
        internal static string ProductImageEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductImageEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have full access to the products and product images.
        /// </summary>
        internal static string ProductMenuAccessAdminNotice {
            get {
                return ResourceManager.GetString("ProductMenuAccessAdminNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have limited access to the products and the product images.
        /// </summary>
        internal static string ProductMenuAccessEmployeeNotice {
            get {
                return ResourceManager.GetString("ProductMenuAccessEmployeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and Product Images list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string ProductMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("ProductMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product orders..
        /// </summary>
        internal static string ProductOrderDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductOrderDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product orders..
        /// </summary>
        internal static string ProductOrderEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductOrderEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate invoice for this product order?.
        /// </summary>
        internal static string ProductOrderInvoiceGenerationQuestion {
            get {
                return ResourceManager.GetString("ProductOrderInvoiceGenerationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Orders list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string ProductOrderMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("ProductOrderMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to override the price of that order as total?.
        /// </summary>
        internal static string ProductOrderTotalPriceOverrideQuestion {
            get {
                return ResourceManager.GetString("ProductOrderTotalPriceOverrideQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?
        ///This operation is irreversible and can cause troubles in the database relations..
        /// </summary>
        internal static string RecordDeletionWarning {
            get {
                return ResourceManager.GetString("RecordDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports cannot be generated or you don&apos;t have permissions to view them..
        /// </summary>
        internal static string ReportGenerationPermissionError {
            get {
                return ResourceManager.GetString("ReportGenerationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generation.
        /// </summary>
        internal static string ReportGenerationTitle {
            get {
                return ResourceManager.GetString("ReportGenerationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk create task executed successfully..
        /// </summary>
        internal static string SampleBulkOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample custom bulk task executed successfully..
        /// </summary>
        internal static string SampleBulkOperationCustomTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationCustomTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk delete task executed successfully..
        /// </summary>
        internal static string SampleBulkOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk update task executed successfully..
        /// </summary>
        internal static string SampleBulkOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: .
        /// </summary>
        internal static string StackTraceMessage {
            get {
                return ResourceManager.GetString("StackTraceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string TestTitle {
            get {
                return ResourceManager.GetString("TestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        internal static string UserAccessTitle {
            get {
                return ResourceManager.GetString("UserAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete users besides your own account..
        /// </summary>
        internal static string UserDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("UserDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit users besides your own account..
        /// </summary>
        internal static string UserEditOperationPermissionError {
            get {
                return ResourceManager.GetString("UserEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string UserMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("UserMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product vendors..
        /// </summary>
        internal static string VendorDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("VendorDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product vendors..
        /// </summary>
        internal static string VendorEditOperationPermissionError {
            get {
                return ResourceManager.GetString("VendorEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendors list access is given only to administrators and employees of this system..
        /// </summary>
        internal static string VendorMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("VendorMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
