//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XtremePharmacyManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the server to update your user account.
        ///Please check your application settings to ensure you have a proper connection to the database or contact a system administrator. .
        /// </summary>
        public static string AccountSettingsErrorMessage {
            get {
                return ResourceManager.GetString("AccountSettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have empty username or password.
        ///If you still can&apos;t update your account ask the administrator for a solution to the problem..
        /// </summary>
        public static string AccountSettingsInvalidCredentialsErrorMessage {
            get {
                return ResourceManager.GetString("AccountSettingsInvalidCredentialsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a profile picture for your account.
        /// </summary>
        public static string AccountSettingsProfilePicSelectTitle {
            get {
                return ResourceManager.GetString("AccountSettingsProfilePicSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string AccountSettingsTitle {
            get {
                return ResourceManager.GetString("AccountSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressColTitle {
            get {
                return ResourceManager.GetString("AddressColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address with which you want to search users.
        /// </summary>
        public static string AddressSearchTooltip {
            get {
                return ResourceManager.GetString("AddressSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of this application can be run at a time!.
        /// </summary>
        public static string ApplicationInstanceErrorMessage {
            get {
                return ResourceManager.GetString("ApplicationInstanceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the application settings will take effect after restarting the application..
        /// </summary>
        public static string ApplicationSettingsChangeNotice {
            get {
                return ResourceManager.GetString("ApplicationSettingsChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save your logins into and load them from.....
        /// </summary>
        public static string ApplicationSettingsLoginsFolderSelectTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsLoginsFolderSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to get the report files from....
        /// </summary>
        public static string ApplicationSettingsReportsFolderSelectTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsReportsFolderSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettingsTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XtremePharmacyManager.
        /// </summary>
        public static string AssemblyProductName {
            get {
                return ResourceManager.GetString("AssemblyProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XtremePharmacyManager.
        /// </summary>
        public static string AssemblyTitle {
            get {
                return ResourceManager.GetString("AssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple login results gotten or none at all.
        ///Please check the credentials and try again..
        /// </summary>
        public static string AuthorisationAddLoginInvalidResultsMessage {
            get {
                return ResourceManager.GetString("AuthorisationAddLoginInvalidResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully found your credentials by the configuration settings of your application.
        ///On your confirmation by logging in this will be the user you will work with.
        ///If you want another user select from the logins list.
        ///Every login is saved into the filesystem in a binary format read only this program..
        /// </summary>
        public static string AuthorisationAppConfLoginFoundMessage {
            get {
                return ResourceManager.GetString("AuthorisationAppConfLoginFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with the specified credentials by your application configuration.
        ///Please configure the application with database credentials provided by your system administrator or create an user with the stored procedures and set it as a sysadmin if you are a system administrator and try again.
        ///The admin role for the database is different from the sysadmin role and this is for security reasons..
        /// </summary>
        public static string AuthorisationAppConfLoginNotFoundMessage {
            get {
                return ResourceManager.GetString("AuthorisationAppConfLoginNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use this application without a proper authorization in the database and closing the login without even confirming or cancelling it will not help you. Application will exit!.
        /// </summary>
        public static string AuthorisationErrorCancelledLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorCancelledLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is only for administrators and employees! 
        ///Client use of it is unauthorized and the application will exit!.
        /// </summary>
        public static string AuthorisationErrorClientLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorClientLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user currently logged in. Application will exit!.
        /// </summary>
        public static string AuthorisationErrorNoLoginMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorNoLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you are the system administrator for the database and you have either disabled or bypassed the logon trigger and that&apos;s why you were probably connected even if you didn&apos;t have credentials to connect to the database.
        ///This might damage the system and enabling the trigger is critical.
        ///This is an important warning because the system is at risk of data breach in multiple ways..
        /// </summary>
        public static string AuthorisationErrorSysAdminBreachMessage {
            get {
                return ResourceManager.GetString("AuthorisationErrorSysAdminBreachMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an administrator.
        ///You have access to everything in the database.
        ///Everything is created, altered and deleted using stored procedures so the database will calculate some of the things for you..
        /// </summary>
        public static string AuthorisationLoginAdminNotice {
            get {
                return ResourceManager.GetString("AuthorisationLoginAdminNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an employee, you have limited access to the features of this application.
        ///Your permissions:
        ///1.Add, edit, delete product images
        ///2.Generate product reports
        ///3.Add, edit, delete and/or generate reports for product orders
        ///4.Add, edit, delete and/or generate reports for order deliveries
        ///5.View logs
        ///6.View the rest of the tables with read-only permissions.
        ///The bulk operations enabled for you are for product images, product orders and order deliveries.
        ///Everything is created, altered and deleted usi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AuthorisationLoginEmployeeNotice {
            get {
                return ResourceManager.GetString("AuthorisationLoginEmployeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you didn&apos;t provide any login information at all.
        ///Please try again..
        /// </summary>
        public static string AuthorisationLoginEmptyInputMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginEmptyInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Logins list hasn&apos;t been retrieved properly.
        ///Please restart the application..
        /// </summary>
        public static string AuthorisationLoginFilesystemLoadErrorMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginFilesystemLoadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with the specified credentials by your input.
        ///Please input the credentials you registered with or provided by your system administrator..
        /// </summary>
        public static string AuthorisationLoginInvalidInputMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginInvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is not connected to the database and login information cannot be retrieved.
        ///Please retry..
        /// </summary>
        public static string AuthorisationLoginNoConnectionMessage {
            get {
                return ResourceManager.GetString("AuthorisationLoginNoConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string BalanceColTitle {
            get {
                return ResourceManager.GetString("BalanceColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The balance with which you want to search users.
        /// </summary>
        public static string BalanceSearchTooltipTitle {
            get {
                return ResourceManager.GetString("BalanceSearchTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDateColTitle {
            get {
                return ResourceManager.GetString("BirthDateColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product brands..
        /// </summary>
        public static string BrandDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("BrandDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product brands..
        /// </summary>
        public static string BrandEditOperationPermissionError {
            get {
                return ResourceManager.GetString("BrandEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand list access is given only to administrators and employees of this system..
        /// </summary>
        public static string BrandMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BrandMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD/EDIT.
        /// </summary>
        public static string BtnAddEditTitle {
            get {
                return ResourceManager.GetString("BtnAddEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click the button you add/edit an entry based on the permissions you have..
        /// </summary>
        public static string BtnAddEditTooltipTitle {
            get {
                return ResourceManager.GetString("BtnAddEditTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string BtnDeleteTitle {
            get {
                return ResourceManager.GetString("BtnDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click the button you delete an entry based on the permissions you have..
        /// </summary>
        public static string BtnDeleteTooltipTitle {
            get {
                return ResourceManager.GetString("BtnDeleteTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE REPORT.
        /// </summary>
        public static string BtnGenerateReportTitle {
            get {
                return ResourceManager.GetString("BtnGenerateReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click the button you generate a report on an entry based on the permissions you have and whether the report definition based on localisation is present..
        /// </summary>
        public static string BtnGenerateReportTooltip {
            get {
                return ResourceManager.GetString("BtnGenerateReportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string BtnSearchTitle {
            get {
                return ResourceManager.GetString("BtnSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you click the button you search based on the criterias search mode you selected..
        /// </summary>
        public static string BtnSearchTooltipTitle {
            get {
                return ResourceManager.GetString("BtnSearchTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Brand Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkBrandMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkBrandMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been added..
        /// </summary>
        public static string BulkBrandOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been deleted..
        /// </summary>
        public static string BulkBrandOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product brands..
        /// </summary>
        public static string BulkBrandOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product brands is done only by the administrators of this system...
        /// </summary>
        public static string BulkBrandOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Brand has been updated..
        /// </summary>
        public static string BulkBrandOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkBrandOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Delivery Service Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkDeliveryServiceMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been added..
        /// </summary>
        public static string BulkDeliveryServiceOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been deleted..
        /// </summary>
        public static string BulkDeliveryServiceOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for delivery services..
        /// </summary>
        public static string BulkDeliveryServiceOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for delivery services is done only by the administrators of this system...
        /// </summary>
        public static string BulkDeliveryServiceOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service has been updated..
        /// </summary>
        public static string BulkDeliveryServiceOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkDeliveryServiceOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operations:.
        /// </summary>
        public static string BulkOperationCompletedCountMessage {
            get {
                return ResourceManager.GetString("BulkOperationCompletedCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations finished. Time finished:.
        /// </summary>
        public static string BulkOperationEndTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationEndTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code:.
        /// </summary>
        public static string BulkOperationErrorCodeMessage {
            get {
                return ResourceManager.GetString("BulkOperationErrorCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        public static string BulkOperationErrorMessage {
            get {
                return ResourceManager.GetString("BulkOperationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing operation:.
        /// </summary>
        public static string BulkOperationExecutingMessage {
            get {
                return ResourceManager.GetString("BulkOperationExecutingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Time:.
        /// </summary>
        public static string BulkOperationExecutionTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationExecutionTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Operations:.
        /// </summary>
        public static string BulkOperationFailedCountMessage {
            get {
                return ResourceManager.GetString("BulkOperationFailedCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. Here are details:.
        /// </summary>
        public static string BulkOperationFailedMessage {
            get {
                return ResourceManager.GetString("BulkOperationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation on.
        /// </summary>
        public static string BulkOperationOperationOnName {
            get {
                return ResourceManager.GetString("BulkOperationOperationOnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ID:.
        /// </summary>
        public static string BulkOperationOperatonOnTargetIDName {
            get {
                return ResourceManager.GetString("BulkOperationOperatonOnTargetIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add this as a bulk operation?.
        /// </summary>
        public static string BulkOperationQuestion {
            get {
                return ResourceManager.GetString("BulkOperationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations Results:.
        /// </summary>
        public static string BulkOperationResultsMessage {
            get {
                return ResourceManager.GetString("BulkOperationResultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations started executing at:.
        /// </summary>
        public static string BulkOperationStartTimeMessage {
            get {
                return ResourceManager.GetString("BulkOperationStartTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Operations.
        /// </summary>
        public static string BulkOperationsTitle {
            get {
                return ResourceManager.GetString("BulkOperationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successful.Output:.
        /// </summary>
        public static string BulkOperationSuccessfulMessage {
            get {
                return ResourceManager.GetString("BulkOperationSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An access exception occured and this operation cannot be executed..
        /// </summary>
        public static string BulkOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Order Delivery Operation access is given only to administrators and employees of this system..
        /// </summary>
        public static string BulkOrderDeliveryMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been added..
        /// </summary>
        public static string BulkOrderDeliveryOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been deleted..
        /// </summary>
        public static string BulkOrderDeliveryOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for order deliveries..
        /// </summary>
        public static string BulkOrderDeliveryOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for order deliveries is done only by the administrators and employees of this system...
        /// </summary>
        public static string BulkOrderDeliveryOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Delivery has been updated..
        /// </summary>
        public static string BulkOrderDeliveryOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkOrderDeliveryOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Payment Method Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkPaymentMethodMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been added..
        /// </summary>
        public static string BulkPaymentMethodOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been deleted..
        /// </summary>
        public static string BulkPaymentMethodOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for payment methods..
        /// </summary>
        public static string BulkPaymentMethodOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for payment methods is done only by the administrators of this system...
        /// </summary>
        public static string BulkPaymentMethodOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method has been updated..
        /// </summary>
        public static string BulkPaymentMethodOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkPaymentMethodOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Image Operation access is given only to administrators and employees of this system..
        /// </summary>
        public static string BulkProductImageMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductImageMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been added..
        /// </summary>
        public static string BulkProductImageOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been deleted..
        /// </summary>
        public static string BulkProductImageOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product images..
        /// </summary>
        public static string BulkProductImageOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product images is done only by the administrators and employees of this system...
        /// </summary>
        public static string BulkProductImageOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image has been updated..
        /// </summary>
        public static string BulkProductImageOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductImageOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkProductMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been added..
        /// </summary>
        public static string BulkProductOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been deleted..
        /// </summary>
        public static string BulkProductOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for products..
        /// </summary>
        public static string BulkProductOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for products is done only by the administrators of this system...
        /// </summary>
        public static string BulkProductOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been updated..
        /// </summary>
        public static string BulkProductOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Order Operation access is given only to administrators and employees of this system..
        /// </summary>
        public static string BulkProductOrderMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been added..
        /// </summary>
        public static string BulkProductOrderOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been deleted..
        /// </summary>
        public static string BulkProductOrderOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product orders..
        /// </summary>
        public static string BulkProductOrderOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product orders is done only by the administrators and employees of this system...
        /// </summary>
        public static string BulkProductOrderOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Order has been updated..
        /// </summary>
        public static string BulkProductOrderOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkProductOrderOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want the bulk order operation to add order with total price override on create?.
        /// </summary>
        public static string BulkProductOrderTotalPriceOverrideQuestion {
            get {
                return ResourceManager.GetString("BulkProductOrderTotalPriceOverrideQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk User Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkUserMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkUserMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added..
        /// </summary>
        public static string BulkUserOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been deleted..
        /// </summary>
        public static string BulkUserOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for users..
        /// </summary>
        public static string BulkUserOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for users is done only by the administrators of this system...
        /// </summary>
        public static string BulkUserOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated..
        /// </summary>
        public static string BulkUserOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkUserOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Product Vendor Operation access is given only to administrators of this system..
        /// </summary>
        public static string BulkVendorMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("BulkVendorMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been added..
        /// </summary>
        public static string BulkVendorOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been deleted..
        /// </summary>
        public static string BulkVendorOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to use bulk operations for product vendors..
        /// </summary>
        public static string BulkVendorOperationNoPermissionMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationNoPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing bulk operations for product vendors is done only by the administrators of this system...
        /// </summary>
        public static string BulkVendorOperationUnauthorisedErrorMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationUnauthorisedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendor has been updated..
        /// </summary>
        public static string BulkVendorOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("BulkVendorOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search modes with which you want to search entries.
        ///All criterias - search by all criterias.
        ///None - show all entries.
        ///Single criteria - entries that are on one criteria with other criterias excluded.
        ///Multiple criterias - with multiple criterias but not all criterias included in the search..
        /// </summary>
        public static string CbSearchModeTooltipTitle {
            get {
                return ResourceManager.GetString("CbSearchModeTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close? All unsaved changes incl. bulk operations will be lost.
        /// </summary>
        public static string ClosePrompt {
            get {
                return ResourceManager.GetString("ClosePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ClosePromptTitle {
            get {
                return ResourceManager.GetString("ClosePromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect even after a retry. Application will exit....
        /// </summary>
        public static string ConnectionFailedAfterRetryMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedAfterRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect and login to the database. 
        ///This was not supposed to happen so contact the system administrator and/or check the application configuration....
        /// </summary>
        public static string ConnectionFailedLoginMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error. 
        ///Please check the application configuration and/or contact your system administrator.
        /// </summary>
        public static string ConnectionFailedMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connection and login to the database. Now you are ready to go..
        /// </summary>
        public static string ConnectionSuccessfulLoginMessage {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successfuly open..
        /// </summary>
        public static string ConnectionSuccessfulMessage {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception details:
        ///.
        /// </summary>
        public static string CriticalErrorInnerExceptionDetails {
            get {
                return ResourceManager.GetString("CriticalErrorInnerExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critcal Error: An exception occured.
        /// </summary>
        public static string CriticalErrorMessage {
            get {
                return ResourceManager.GetString("CriticalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        public static string CriticalErrorTitle {
            get {
                return ResourceManager.GetString("CriticalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Host.
        /// </summary>
        public static string CurrentHostTitle {
            get {
                return ResourceManager.GetString("CurrentHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Operator.
        /// </summary>
        public static string CurrentOperatorTitle {
            get {
                return ResourceManager.GetString("CurrentOperatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete delivery services..
        /// </summary>
        public static string DeliveryServiceDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("DeliveryServiceDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit delivery services..
        /// </summary>
        public static string DeliveryServiceEditOperationPermissionError {
            get {
                return ResourceManager.GetString("DeliveryServiceEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Service list access is given only to administrators and employees of this system..
        /// </summary>
        public static string DeliveryServiceMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("DeliveryServiceMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of users in the database. Select any to add/edit/delete/generate report based on your permissions..
        /// </summary>
        public static string DgvUsersTooltipTitle {
            get {
                return ResourceManager.GetString("DgvUsersTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose.
        /// </summary>
        public static string DiagnoseColTitle {
            get {
                return ResourceManager.GetString("DiagnoseColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnose with which you want to search users.
        /// </summary>
        public static string DiagnoseSearchTooltip {
            get {
                return ResourceManager.GetString("DiagnoseSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayNameColTitle {
            get {
                return ResourceManager.GetString("DisplayNameColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display name with which you want to search users.
        /// </summary>
        public static string DisplayNameSearchTooltip {
            get {
                return ResourceManager.GetString("DisplayNameSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailColTitle {
            get {
                return ResourceManager.GetString("EmailColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email with which you want to search users.
        /// </summary>
        public static string EmailSearchTooltip {
            get {
                return ResourceManager.GetString("EmailSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTooltipTitle {
            get {
                return ResourceManager.GetString("HelpTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the selected record entry to be searched is here.
        /// </summary>
        public static string IDSearchTooltip {
            get {
                return ResourceManager.GetString("IDSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image to test the conversion capabilities...
        /// </summary>
        public static string ImageBinConverterConvertImageTitle {
            get {
                return ResourceManager.GetString("ImageBinConverterConvertImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image to upload or for add/update operation....
        /// </summary>
        public static string ImageUploadForOperationTitle {
            get {
                return ResourceManager.GetString("ImageUploadForOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language already exists!.
        /// </summary>
        public static string LanguageManagerLanguageExistErrorMessage {
            get {
                return ResourceManager.GetString("LanguageManagerLanguageExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This language wasn&apos;t added in the first place or was removed.
        /// </summary>
        public static string LanguageManagerLanguageNonexistentErrorMessage {
            get {
                return ResourceManager.GetString("LanguageManagerLanguageNonexistentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string LblAddressTitle {
            get {
                return ResourceManager.GetString("LblAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string LblBalanceTitle {
            get {
                return ResourceManager.GetString("LblBalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Results:.
        /// </summary>
        public static string lblBulkOperationResultsText {
            get {
                return ResourceManager.GetString("lblBulkOperationResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose:.
        /// </summary>
        public static string LblDiagnoseTitle {
            get {
                return ResourceManager.GetString("LblDiagnoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name:.
        /// </summary>
        public static string LblDisplayNameTitle {
            get {
                return ResourceManager.GetString("LblDisplayNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string LblEmailTitle {
            get {
                return ResourceManager.GetString("LblEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string LblIDTitle {
            get {
                return ResourceManager.GetString("LblIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LblPasswordTitle {
            get {
                return ResourceManager.GetString("LblPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string LblPhoneTitle {
            get {
                return ResourceManager.GetString("LblPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string LblRoleAdmin {
            get {
                return ResourceManager.GetString("LblRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string LblRoleClient {
            get {
                return ResourceManager.GetString("LblRoleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string LblRoleEmployee {
            get {
                return ResourceManager.GetString("LblRoleEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string LblRoleTitle {
            get {
                return ResourceManager.GetString("LblRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Criterias.
        /// </summary>
        public static string LblSearchModeAll {
            get {
                return ResourceManager.GetString("LblSearchModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Criterias.
        /// </summary>
        public static string LblSearchModeMultiple {
            get {
                return ResourceManager.GetString("LblSearchModeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LblSearchModeNone {
            get {
                return ResourceManager.GetString("LblSearchModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Criteria.
        /// </summary>
        public static string LblSearchModeSingle {
            get {
                return ResourceManager.GetString("LblSearchModeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode:.
        /// </summary>
        public static string LblSearchModeTitle {
            get {
                return ResourceManager.GetString("LblSearchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date From:.
        /// </summary>
        public static string LblUserBDateFromTitle {
            get {
                return ResourceManager.GetString("LblUserBDateFromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date To:.
        /// </summary>
        public static string LblUserBDateToTitle {
            get {
                return ResourceManager.GetString("LblUserBDateToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string LblUsernameTitle {
            get {
                return ResourceManager.GetString("LblUsernameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT NOTICE:
        ///Username and password
        ///should be unique.
        /// </summary>
        public static string LblUserNoticeTitle {
            get {
                return ResourceManager.GetString("LblUserNoticeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered On From:.
        /// </summary>
        public static string LblUserRegDateFromTitle {
            get {
                return ResourceManager.GetString("LblUserRegDateFromTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered On To:.
        /// </summary>
        public static string LblUserRegDateToTitle {
            get {
                return ResourceManager.GetString("LblUserRegDateToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Logs access is given only to administrators and employees of this system..
        /// </summary>
        public static string LogsMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("LogsMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string NewOrderTitle {
            get {
                return ResourceManager.GetString("NewOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete order deliveries..
        /// </summary>
        public static string OrderDeliveryDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("OrderDeliveryDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit order deliveries..
        /// </summary>
        public static string OrderDeliveryEditOperationPermissionError {
            get {
                return ResourceManager.GetString("OrderDeliveryEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate invoice for this order delivery?.
        /// </summary>
        public static string OrderDeliveryInvoiceGenerationQuestion {
            get {
                return ResourceManager.GetString("OrderDeliveryInvoiceGenerationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Deliveries list access is given only to administrators and employees of this system..
        /// </summary>
        public static string OrderDeliveryMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("OrderDeliveryMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordColTitle {
            get {
                return ResourceManager.GetString("PasswordColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password with which you want to search users.
        /// </summary>
        public static string PasswordSearchTooltip {
            get {
                return ResourceManager.GetString("PasswordSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete payment methods..
        /// </summary>
        public static string PaymentMethodDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("PaymentMethodDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit payment methods..
        /// </summary>
        public static string PaymentMethodEditOperationPermissionError {
            get {
                return ResourceManager.GetString("PaymentMethodEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method list access is given only to administrators and employees of this system..
        /// </summary>
        public static string PaymentMethodMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("PaymentMethodMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneColTitle {
            get {
                return ResourceManager.GetString("PhoneColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone with which you want to search users.
        /// </summary>
        public static string PhoneSearchTooltip {
            get {
                return ResourceManager.GetString("PhoneSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete products..
        /// </summary>
        public static string ProductDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit products..
        /// </summary>
        public static string ProductEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product images..
        /// </summary>
        public static string ProductImageDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductImageDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product images..
        /// </summary>
        public static string ProductImageEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductImageEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have full access to the products and product images.
        /// </summary>
        public static string ProductMenuAccessAdminNotice {
            get {
                return ResourceManager.GetString("ProductMenuAccessAdminNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have limited access to the products and the product images.
        /// </summary>
        public static string ProductMenuAccessEmployeeNotice {
            get {
                return ResourceManager.GetString("ProductMenuAccessEmployeeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products and Product Images list access is given only to administrators and employees of this system..
        /// </summary>
        public static string ProductMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("ProductMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product orders..
        /// </summary>
        public static string ProductOrderDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductOrderDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product orders..
        /// </summary>
        public static string ProductOrderEditOperationPermissionError {
            get {
                return ResourceManager.GetString("ProductOrderEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate invoice for this product order?.
        /// </summary>
        public static string ProductOrderInvoiceGenerationQuestion {
            get {
                return ResourceManager.GetString("ProductOrderInvoiceGenerationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Orders list access is given only to administrators and employees of this system..
        /// </summary>
        public static string ProductOrderMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("ProductOrderMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to override the price of that order as total?.
        /// </summary>
        public static string ProductOrderTotalPriceOverrideQuestion {
            get {
                return ResourceManager.GetString("ProductOrderTotalPriceOverrideQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicColTitle {
            get {
                return ResourceManager.GetString("ProfilePicColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?
        ///This operation is irreversible and can cause troubles in the database relations..
        /// </summary>
        public static string RecordDeletionWarning {
            get {
                return ResourceManager.GetString("RecordDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string RegisterDateColTitle {
            get {
                return ResourceManager.GetString("RegisterDateColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports cannot be generated or you don&apos;t have permissions to view them..
        /// </summary>
        public static string ReportGenerationPermissionError {
            get {
                return ResourceManager.GetString("ReportGenerationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generation.
        /// </summary>
        public static string ReportGenerationTitle {
            get {
                return ResourceManager.GetString("ReportGenerationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleColTitle {
            get {
                return ResourceManager.GetString("RoleColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role in the system with which you want to search users.
        /// </summary>
        public static string RoleSearchTooltip {
            get {
                return ResourceManager.GetString("RoleSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk create task executed successfully..
        /// </summary>
        public static string SampleBulkOperationCreateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationCreateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample custom bulk task executed successfully..
        /// </summary>
        public static string SampleBulkOperationCustomTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationCustomTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk delete task executed successfully..
        /// </summary>
        public static string SampleBulkOperationDeleteTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationDeleteTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample bulk update task executed successfully..
        /// </summary>
        public static string SampleBulkOperationUpdateTaskSuccessMessage {
            get {
                return ResourceManager.GetString("SampleBulkOperationUpdateTaskSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: .
        /// </summary>
        public static string StackTraceMessage {
            get {
                return ResourceManager.GetString("StackTraceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestTitle {
            get {
                return ResourceManager.GetString("TestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access.
        /// </summary>
        public static string UserAccessTitle {
            get {
                return ResourceManager.GetString("UserAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birth date from which you want to search users.
        /// </summary>
        public static string UserBDateFromSearchTooltip {
            get {
                return ResourceManager.GetString("UserBDateFromSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birth date to which you want to search users.
        /// </summary>
        public static string UserBDateToSearchTooltip {
            get {
                return ResourceManager.GetString("UserBDateToSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete users besides your own account..
        /// </summary>
        public static string UserDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("UserDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit users besides your own account..
        /// </summary>
        public static string UserEditOperationPermissionError {
            get {
                return ResourceManager.GetString("UserEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserIDColTitle {
            get {
                return ResourceManager.GetString("UserIDColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list access is given only to administrators and employees of this system..
        /// </summary>
        public static string UserMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("UserMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserNameColTitle {
            get {
                return ResourceManager.GetString("UserNameColTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username with which you want to search users.
        /// </summary>
        public static string UsernameSearchTooltip {
            get {
                return ResourceManager.GetString("UsernameSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a dumbfuck like my creator read this so you don&apos;t complain that you can&apos;t change the user data via any operation.
        /// </summary>
        public static string UserNoticeTooltipTitle {
            get {
                return ResourceManager.GetString("UserNoticeTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration date from which you want to search users.
        /// </summary>
        public static string UserRegDateFromSearchTooltip {
            get {
                return ResourceManager.GetString("UserRegDateFromSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration date to which you want to search users.
        /// </summary>
        public static string UserRegDateToSearchTooltip {
            get {
                return ResourceManager.GetString("UserRegDateToSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTitle {
            get {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The users window where you can search, add, edit, delete and generate reports on the users. Whether you can do it or not depends on your permissions.
        /// </summary>
        public static string UsersTooltipTitle {
            get {
                return ResourceManager.GetString("UsersTooltipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to delete product vendors..
        /// </summary>
        public static string VendorDeleteOperationPermissionError {
            get {
                return ResourceManager.GetString("VendorDeleteOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to add/edit product vendors..
        /// </summary>
        public static string VendorEditOperationPermissionError {
            get {
                return ResourceManager.GetString("VendorEditOperationPermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Vendors list access is given only to administrators and employees of this system..
        /// </summary>
        public static string VendorMenuAccessErrorMessage {
            get {
                return ResourceManager.GetString("VendorMenuAccessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
