//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientView
    {
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserDisplayName { get; set; }
        public System.DateTime UserBirthDate { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserAddress { get; set; }
        public byte[] UserProfilePic { get; set; }
        public decimal UserBalance { get; set; }
        public string UserDiagnose { get; set; }
        public System.DateTime UserDateOfRegister { get; set; }
        public int UserRole { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> AverageClientSpending { get; set; }
        public Nullable<decimal> AverageClientRefund { get; set; }
        public Nullable<decimal> EstimatedAverageClientSpending { get; set; }
        public Nullable<decimal> AverageSpendingOfAllClients { get; set; }
        public Nullable<decimal> AverageRefundOfAllClients { get; set; }
        public Nullable<decimal> EstimatedAverageSpendingOfAllClients { get; set; }
        public Nullable<decimal> TotalClientSpending { get; set; }
        public Nullable<decimal> TotalClientRefund { get; set; }
        public Nullable<decimal> EstimatedTotalClientSpending { get; set; }
        public Nullable<decimal> TotalSpendingOfAllClients { get; set; }
        public Nullable<decimal> TotalRefundOfAllClients { get; set; }
        public Nullable<decimal> EstimatedTotalSpendingOfClients { get; set; }
        public Nullable<int> AverageQuantityBought { get; set; }
        public Nullable<int> AverageQuantityReturned { get; set; }
        public Nullable<int> AverageQuantityOrdered { get; set; }
        public Nullable<int> AverageQuantityBoughtByAllClients { get; set; }
        public Nullable<int> AverageQuantityReturnedByAllClients { get; set; }
        public Nullable<int> AverageQuantityOrderedByAllClients { get; set; }
        public Nullable<int> TotalQuantityBought { get; set; }
        public Nullable<int> TotalQuantityReturned { get; set; }
        public Nullable<int> TotalQuantityOrdered { get; set; }
        public Nullable<int> TotalQuantityBoughtByAllEmployees { get; set; }
        public Nullable<int> TotalQuantityReturnedByAllEmployees { get; set; }
        public Nullable<int> TotalQuantityOrderedByAllEmployees { get; set; }
        public Nullable<int> ProductsBoughtByThisClient { get; set; }
        public Nullable<int> ProductsReturnedByThisClient { get; set; }
        public Nullable<int> ProductsOrderedByThisClient { get; set; }
        public Nullable<int> ProductsBoughtByAllClients { get; set; }
        public Nullable<int> ProductsReturnedByAllClients { get; set; }
        public Nullable<int> ProductsOrderedByAllClients { get; set; }
        public Nullable<int> EmployeesThatCompletedOrdersForThisClient { get; set; }
        public Nullable<int> EmployeesThatCancelledOrReturnedOrdersForThisClient { get; set; }
        public Nullable<int> EmployeesThatWereAssignedToThisClient { get; set; }
        public Nullable<int> EmployeesThatCompletedOrdersForAllCLients { get; set; }
        public Nullable<int> EmployeesThatReturnedOrdersForAllClients { get; set; }
        public Nullable<int> EmployeesThatWereAssignedToAllClients { get; set; }
        public Nullable<decimal> TotalClientInvestment { get; set; }
        public Nullable<decimal> AverageClientSpendingRateByItsAverageEstimatedSpending { get; set; }
        public Nullable<decimal> AverageClientRefundRateByItsAverageEstimatedSpending { get; set; }
        public Nullable<decimal> AverageClientSpendingRateByGlobalAverageEstimatedSpending { get; set; }
        public Nullable<decimal> AverageClientRefundRateByGlobalAverageEstimatedSpending { get; set; }
        public Nullable<decimal> GlobalAverageClientSpendingRate { get; set; }
        public Nullable<decimal> GlobalAverageClientRefundRate { get; set; }
        public Nullable<decimal> EstimatedAverageInvestmentRate { get; set; }
        public Nullable<decimal> AverageQuantityBuyRateByItsAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageQuantityReturnRateByItsAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageQuantityBuyRateByGlobalAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageQuantityReturnRateByGlobalAverageOrderedQuantity { get; set; }
        public Nullable<decimal> GlobalAverageQuantityBuyRate { get; set; }
        public Nullable<decimal> GlobalAverageQuantityReturnRate { get; set; }
        public Nullable<decimal> AverageQuantityOrderRate { get; set; }
        public Nullable<decimal> TotalClientSpendingRateByItsTotalEstimatedSpending { get; set; }
        public Nullable<decimal> TotalClientRefundRateByItsTotalEstimatedSpending { get; set; }
        public Nullable<decimal> TotalClientSpendingRateByTotalGlobalEstimatedSpending { get; set; }
        public Nullable<decimal> TotalClientRefundRateByTotalGlobalEstimatedSpending { get; set; }
        public Nullable<decimal> GlobalTotalClientSpendingRate { get; set; }
        public Nullable<decimal> GlobalTotalClientRefundRate { get; set; }
        public Nullable<decimal> EstimatedTotalInvestmentRate { get; set; }
        public Nullable<decimal> TotalQuantityBuyRateByItsTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalQuantityReturnRateByItsTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalQuantityBuyRateByGlobalTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalQuantityReturnRateByGlobalTotalOrderedQuantity { get; set; }
        public Nullable<decimal> GlobalTotalQuantityBuyRate { get; set; }
        public Nullable<decimal> GlobalTotalQuantityReturnRate { get; set; }
        public Nullable<decimal> TotalQuantityOrderRate { get; set; }
        public Nullable<decimal> ProductOrderCompletionRateByItsOrderedProducts { get; set; }
        public Nullable<decimal> ProductOrderCancellationRateByItsOrderedProducts { get; set; }
        public Nullable<decimal> ProductOrderCompletionRateByGlobalOrderedProducts { get; set; }
        public Nullable<decimal> ProductOrderCancellationRateByGlobalOrderedProducts { get; set; }
        public Nullable<decimal> GlobalProductOrderCompletionRate { get; set; }
        public Nullable<decimal> GlobalProductOrderCancellationRate { get; set; }
        public Nullable<decimal> TotalProductOrderRate { get; set; }
        public Nullable<decimal> ClientSatisfactionRateByEmployeesWhoProcessedTheirOrders { get; set; }
        public Nullable<decimal> ClientDissatisfactionRateByEmployeesWhoProcessedTheirOrders { get; set; }
        public Nullable<decimal> ClientSatisfactionRateByGlobalProcessingCount { get; set; }
        public Nullable<decimal> ClientDissatisfactionRateByGlobalProcessingCount { get; set; }
        public Nullable<decimal> GlobalClientSatisfactionRate { get; set; }
        public Nullable<decimal> GlobalClientDissatisfactionRate { get; set; }
        public Nullable<decimal> TotalEmployeeProcessRate { get; set; }
        public Nullable<decimal> ClientBalanceRate { get; set; }
    }
}
