//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserDisplayName { get; set; }
        public System.DateTime UserBirthDate { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public string UserAddress { get; set; }
        public byte[] UserProfilePic { get; set; }
        public decimal UserBalance { get; set; }
        public string UserDiagnose { get; set; }
        public System.DateTime UserDateOfRegister { get; set; }
        public int UserRole { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> AverageEmployeeIncome { get; set; }
        public Nullable<decimal> AverageEmployeeLoss { get; set; }
        public Nullable<decimal> EstimatedAverageEmployeeIncome { get; set; }
        public Nullable<decimal> AverageIncomeOfAllEmployees { get; set; }
        public Nullable<decimal> AverageLossOfAllEmployees { get; set; }
        public Nullable<decimal> EstimatedAverageIncomeOfAllEmployees { get; set; }
        public Nullable<decimal> TotalEmployeeIncome { get; set; }
        public Nullable<decimal> TotalEmployeeLoss { get; set; }
        public Nullable<decimal> EstimatedTotalEmployeeIncome { get; set; }
        public Nullable<decimal> TotalIncomeOfAllEmployees { get; set; }
        public Nullable<decimal> TotalLossOfAllEmployees { get; set; }
        public Nullable<decimal> EstimatedTotalIncomeOfAllEmployees { get; set; }
        public Nullable<int> AverageQuantitySold { get; set; }
        public Nullable<int> AverageQuantityReturned { get; set; }
        public Nullable<int> AverageQuantityAssigned { get; set; }
        public Nullable<int> AverageQuantitySoldByAllEmployees { get; set; }
        public Nullable<int> AverageQuantityReturnedByAllEmployees { get; set; }
        public Nullable<int> AverageQuantityAssignedToAllEmployees { get; set; }
        public Nullable<int> TotalQuantitySold { get; set; }
        public Nullable<int> TotalQuantityReturned { get; set; }
        public Nullable<int> TotalQuantityAssigned { get; set; }
        public Nullable<int> TotalQuantitySoldByAllEmployees { get; set; }
        public Nullable<int> TotalQuantityReturnedByAllEmployees { get; set; }
        public Nullable<int> TotalQuantityAssignedToAllEmployees { get; set; }
        public Nullable<int> ProductsSoldByThisEmployee { get; set; }
        public Nullable<int> ProductsReturnedByThisEmployee { get; set; }
        public Nullable<int> ProductsAssignedToThisEmployee { get; set; }
        public Nullable<int> ProductsSoldByAllEmployees { get; set; }
        public Nullable<int> ProductsReturnedByAllEmployees { get; set; }
        public Nullable<int> ProductsAssignedToAllEmployees { get; set; }
        public Nullable<int> ClientsThatThisEmployeeCompletedOrdersFor { get; set; }
        public Nullable<int> ClientsThatThisEmployeeReturnedOrdersFor { get; set; }
        public Nullable<int> ClientsAssignedToThisEmployee { get; set; }
        public Nullable<int> ClientsThatAllEmployeesCompletedOrdersFor { get; set; }
        public Nullable<int> ClientsThatAllEmployeesReturnedOrdersFor { get; set; }
        public Nullable<int> ClientsAssignedToAllEmployees { get; set; }
        public Nullable<decimal> TotalCompanyBalance { get; set; }
        public Nullable<decimal> AverageEmployeeIncomeRateByItsAverageEstimatedIncome { get; set; }
        public Nullable<decimal> AverageEmployeeLossRateByItsAverageEstimatedIncome { get; set; }
        public Nullable<decimal> AverageEmployeeIncomeRateByGlobalAverageEstimatedIncome { get; set; }
        public Nullable<decimal> AverageEmployeeLossRateByGlobalAverageEstimatedIncome { get; set; }
        public Nullable<decimal> GlobalAverageEmployeeIncomeRate { get; set; }
        public Nullable<decimal> GlobalAverageEmployeeLossRate { get; set; }
        public Nullable<decimal> EstimatedAveragePaymentRate { get; set; }
        public Nullable<decimal> AverageQuantitySaleRateByItsAverageAssignedQuantity { get; set; }
        public Nullable<decimal> AverageQuantityReturnRateByItsAverageAssignedQuantity { get; set; }
        public Nullable<decimal> AverageQuantitySaleRateByGlobalAverageAssignedQuantity { get; set; }
        public Nullable<decimal> AverageQuantityReturnRateByGlobalAverageAssignedQuantity { get; set; }
        public Nullable<decimal> GlobalAverageQuantitySellRate { get; set; }
        public Nullable<decimal> GlobalAverageQuantityReturnRate { get; set; }
        public Nullable<decimal> AverageQuantityAssignRate { get; set; }
        public Nullable<decimal> TotalEmployeeIncomeRateByItsTotalEstimatedIncome { get; set; }
        public Nullable<decimal> TotalEmployeeLossRateByItsTotalEstimatedIncome { get; set; }
        public Nullable<decimal> TotalEmployeeIncomeRateByTotalGlobalEstimatedIncome { get; set; }
        public Nullable<decimal> TotalEmployeeLossRateByTotalGlobalEstimatedIncome { get; set; }
        public Nullable<decimal> GlobalTotalEmployeeIncomeRate { get; set; }
        public Nullable<decimal> GlobalTotalEmployeeLossRate { get; set; }
        public Nullable<decimal> EstimatedTotalPaymentRate { get; set; }
        public Nullable<decimal> TotalQuantitySaleRateByItsTotalAssignedQuantity { get; set; }
        public Nullable<decimal> TotalQuantityReturnRateByItsTotalAssignedQuantity { get; set; }
        public Nullable<decimal> TotalQuantitySaleRateByGlobalTotalAssignedQuantity { get; set; }
        public Nullable<decimal> TotalQuantityReturnRateByGlobalTotalAssignedQuantity { get; set; }
        public Nullable<decimal> GlobalTotalQuantitySellRate { get; set; }
        public Nullable<decimal> GlobalTotalQuantityReturnRate { get; set; }
        public Nullable<decimal> TotalQuantityAssignRate { get; set; }
        public Nullable<decimal> ProductOrderCompletionRateByItsAssignedProducts { get; set; }
        public Nullable<decimal> ProductOrderCancellationRateByItsAssignedProducts { get; set; }
        public Nullable<decimal> ProductOrderCompletionRateByGlobalAssignedProducts { get; set; }
        public Nullable<decimal> ProductOrderCancellationRateByGlobalAssignedProducts { get; set; }
        public Nullable<decimal> GlobalProductOrderCompletionRate { get; set; }
        public Nullable<decimal> GlobalProductOrderCancellationRate { get; set; }
        public Nullable<decimal> TotalProductAssignRate { get; set; }
        public Nullable<decimal> ClientSatisfactionRateByItsAssignedClients { get; set; }
        public Nullable<decimal> ClientDissatisfactionRateByItsAssignedClients { get; set; }
        public Nullable<decimal> ClientSatisfactionRateByGlobalAssignedClients { get; set; }
        public Nullable<decimal> ClientDissatisfactionRateByGlobalAssignedClients { get; set; }
        public Nullable<decimal> GlobalClientSatisfactionRate { get; set; }
        public Nullable<decimal> GlobalClientDissatisfactionRate { get; set; }
        public Nullable<decimal> TotalClientAssignRate { get; set; }
        public Nullable<decimal> EmployeeBalanceRate { get; set; }
    }
}
