//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedProductView
    {
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductQuantity { get; set; }
        public decimal ProductPrice { get; set; }
        public System.DateTime ProductExpiryDate { get; set; }
        public string ProductRegNum { get; set; }
        public string ProductPartNum { get; set; }
        public string ProductStorageLocation { get; set; }
        public Nullable<decimal> AverageProductSale { get; set; }
        public Nullable<int> ProductImageCount { get; set; }
    }
}
