//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class ExtendedDeliveryServicesView
    {
        public string ServiceName { get; set; }
        public decimal ServicePrice { get; set; }
        public int ID { get; set; }
    }
}
