//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedProductView
    {
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductQuantity { get; set; }
        public decimal ProductPrice { get; set; }
        public System.DateTime ProductExpiryDate { get; set; }
        public string ProductRegNum { get; set; }
        public string ProductPartNum { get; set; }
        public string ProductStorageLocation { get; set; }
        public Nullable<decimal> AverageProductSale { get; set; }
        public Nullable<int> ProductImageCount { get; set; }
        public int ID { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> AverageProductOrderSale { get; set; }
        public Nullable<decimal> AverageProductOrderReturn { get; set; }
        public Nullable<decimal> AverageProductOrderCost { get; set; }
        public Nullable<decimal> AverageOrderSaleOfAllProducts { get; set; }
        public Nullable<decimal> AverageOrderReturnOfAllProducts { get; set; }
        public Nullable<decimal> AverageOrderCostOfAllProducts { get; set; }
        public Nullable<decimal> AverageProductReturn { get; set; }
        public Nullable<decimal> AverageProductCost { get; set; }
        public Nullable<decimal> AverageSaleOfAllProducts { get; set; }
        public Nullable<decimal> AverageReturnOfAllProducts { get; set; }
        public Nullable<decimal> AverageCostOfAllProducts { get; set; }
        public Nullable<int> AverageProductOutbound { get; set; }
        public Nullable<int> AverageProductInbound { get; set; }
        public Nullable<int> AverageOrderedQuantityOfThisProduct { get; set; }
        public Nullable<int> AverageOutboundOfAllProducts { get; set; }
        public Nullable<int> AverageInboundOfAllProducts { get; set; }
        public Nullable<int> AverageOrderedQuantityOfAllProducts { get; set; }
        public Nullable<int> ProductAcceptCount { get; set; }
        public Nullable<int> ProductReturnCount { get; set; }
        public Nullable<int> ProductOrderCount { get; set; }
        public Nullable<int> AcceptCountOfAllProducts { get; set; }
        public Nullable<int> ReturnCountOfAllProducts { get; set; }
        public Nullable<int> OrderCountOfAllProducts { get; set; }
        public Nullable<int> TimesOfSaleOfThisProduct { get; set; }
        public Nullable<int> TimesOfReturnOfThisProduct { get; set; }
        public Nullable<int> TimesOfOrderOfProduct { get; set; }
        public Nullable<int> TimesOfSaleOfAllProducts { get; set; }
        public Nullable<int> TimesOfReturnOfAllProducts { get; set; }
        public Nullable<int> TimesOfOrderOfAllProducts { get; set; }
        public Nullable<decimal> TotalProductOrderSale { get; set; }
        public Nullable<decimal> TotalProductOrderReturn { get; set; }
        public Nullable<decimal> TotalProductOrderCost { get; set; }
        public Nullable<decimal> TotalOrderSaleOfAllProducts { get; set; }
        public Nullable<decimal> TotalOrderReturnOfAllProducts { get; set; }
        public Nullable<decimal> TotalOrderCostOfAllProducts { get; set; }
        public Nullable<decimal> TotalProductSale { get; set; }
        public Nullable<decimal> TotalProductReturn { get; set; }
        public Nullable<decimal> TotalProductCost { get; set; }
        public Nullable<decimal> TotalSaleOfAllProducts { get; set; }
        public Nullable<decimal> TotalReturnOfAllProducts { get; set; }
        public Nullable<decimal> TotalCostOfAllProducts { get; set; }
        public Nullable<int> TotalProductOutbound { get; set; }
        public Nullable<int> TotalProductInbound { get; set; }
        public Nullable<int> TotalProductOrderQuantity { get; set; }
        public Nullable<int> TotalOutboundOfAllProducts { get; set; }
        public Nullable<int> TotalInboundOfAllProducts { get; set; }
        public Nullable<int> TotalOrderQuantityOfAllProducts { get; set; }
        public Nullable<int> ImageCountOfAllProducts { get; set; }
        public Nullable<int> TotalProductStorageQuantity { get; set; }
        public Nullable<decimal> AverageProductOrderSaleRateByItsAverageOrderCost { get; set; }
        public Nullable<decimal> AverageProductOrderReturnRateByItsAverageOrderCost { get; set; }
        public Nullable<decimal> AverageProductOrderSaleRateByGlobalAverageOrderCost { get; set; }
        public Nullable<decimal> AverageProductOrderReturnRateByGlobalAverageOrderCost { get; set; }
        public Nullable<decimal> GlobalAverageProductOrderSaleRate { get; set; }
        public Nullable<decimal> GlobalAverageProductOrderReturnRate { get; set; }
        public Nullable<decimal> AverageProductOrderCostRate { get; set; }
        public Nullable<decimal> AverageProductSaleRateByItsAverageCost { get; set; }
        public Nullable<decimal> AverageProductReturnRateByItsAverageCost { get; set; }
        public Nullable<decimal> AverageProductSaleRateByGlobalAverageCost { get; set; }
        public Nullable<decimal> AverageProductReturnRateByGlobalAverageCost { get; set; }
        public Nullable<decimal> GlobalAverageProductSaleRate { get; set; }
        public Nullable<decimal> GlobalAverageProductReturnRate { get; set; }
        public Nullable<decimal> AverageProductCostRate { get; set; }
        public Nullable<decimal> AverageProductOutboundRateByItsAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageProductInboundRateByItsAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageProductOutboundRateByGlobalAverageOrderedQuantity { get; set; }
        public Nullable<decimal> AverageProductInboundRateByGlobalAverageOrderedQuantity { get; set; }
        public Nullable<decimal> GlobalAverageProductOutboundRate { get; set; }
        public Nullable<decimal> GlobalAverageProductInboundRate { get; set; }
        public Nullable<decimal> AverageProductOrderQuantityRate { get; set; }
        public Nullable<decimal> TotalProductOrderSaleRateByItsTotalOrderCost { get; set; }
        public Nullable<decimal> TotalProductOrderReturnRateByItsTotalOrderCost { get; set; }
        public Nullable<decimal> TotalProductOrderSaleRateByGlobalTotalOrderCost { get; set; }
        public Nullable<decimal> TotalProductOrderReturnRateByGlobalTotalOrderCost { get; set; }
        public Nullable<decimal> GlobalTotalProductOrderSaleRate { get; set; }
        public Nullable<decimal> GlobalTotalProductOrderReturnRate { get; set; }
        public Nullable<decimal> TotalProductOrderCostRate { get; set; }
        public Nullable<decimal> TotalProductSaleRateByItsTotalCost { get; set; }
        public Nullable<decimal> TotalProductReturnRateByItsTotalCost { get; set; }
        public Nullable<decimal> TotalProductSaleRateByGlobalTotalCost { get; set; }
        public Nullable<decimal> TotalProductReturnRateByGlobalTotalCost { get; set; }
        public Nullable<decimal> GlobalTotalProductSaleRate { get; set; }
        public Nullable<decimal> GlobalTotalProductReturnRate { get; set; }
        public Nullable<decimal> TotalProductCostRate { get; set; }
        public Nullable<decimal> TotalProductOutboundRateByItsTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalProductInboundRateByItsTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalProductOutboundRateByGlobalTotalOrderedQuantity { get; set; }
        public Nullable<decimal> TotalProductInboundRateByGlobalTotalOrderedQuantity { get; set; }
        public Nullable<decimal> GlobalTotalProductOutboundRate { get; set; }
        public Nullable<decimal> GlobalTotalProductInboundRate { get; set; }
        public Nullable<decimal> TotalProductQuantityRate { get; set; }
        public Nullable<decimal> ProductAcceptRateByItsClientNumbers { get; set; }
        public Nullable<decimal> ProductReturnRateByItsClientNumbers { get; set; }
        public Nullable<decimal> ProductSaleRateByGlobalClientNumbers { get; set; }
        public Nullable<decimal> ProductReturnRateByGlobalClientNumbers { get; set; }
        public Nullable<decimal> GlobalProductSaleRateByClientNumbers { get; set; }
        public Nullable<decimal> GlobalProductReturnRateByClientNumbers { get; set; }
        public Nullable<decimal> ProductOrderRateByClientNumbers { get; set; }
        public Nullable<decimal> ProductSellTimesRateByItsOrderTimes { get; set; }
        public Nullable<decimal> ProductReturnTimesRateByItsOrderTimes { get; set; }
        public Nullable<decimal> ProductSaleTimesRateByGlobalOrderTimes { get; set; }
        public Nullable<decimal> ProductReturnTimesRateByGlobalOrderTimes { get; set; }
        public Nullable<decimal> GlobalProductSaleTimesRate { get; set; }
        public Nullable<decimal> GlobalProductReturnTimesRateByClientNumbers { get; set; }
        public Nullable<decimal> ProductOrderTimesRate { get; set; }
        public Nullable<decimal> ProductImageCountRate { get; set; }
        public Nullable<decimal> ProductStorageQuantityRate { get; set; }
    }
}
