//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePharmacyManager.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtendedOrderDeliveriesView
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string BrandName { get; set; }
        public string ProductDescription { get; set; }
        public System.DateTime ProductExpiryDate { get; set; }
        public int DesiredQuantity { get; set; }
        public decimal OrderPrice { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public string ClientEmail { get; set; }
        public string ClientAddress { get; set; }
        public string EmployeeName { get; set; }
        public string ServiceName { get; set; }
        public decimal DeliveryPrice { get; set; }
        public string MethodName { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public int DeliveryStatus { get; set; }
        public string DeliveryReason { get; set; }
        public string CargoID { get; set; }
        public string VendorName { get; set; }
    }
}
